from os import error, getcwd
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,ttk
import tkinter as tk







LARGEFONT =("Verdana", 35)

class tkinterApp(tk.Tk):
	
	# __init__ function for class tkinterApp 
	def __init__(self, *args, **kwargs): 
		
		# __init__ function for class Tk
		tk.Tk.__init__(self, *args, **kwargs)
		
		# creating a container
		container = tk.Frame(self) 
		container.pack(side = "top", fill = "both", expand = True) 

		container.grid_rowconfigure(0, weight = 1)
		container.grid_columnconfigure(0, weight = 1)

		# initializing frames to an empty array
		self.frames = {} 

		# iterating through a tuple consisting
		# of the different page layouts
		for F in (StartPage, Page1, Page2):

			frame = F(container, self)

			# initializing frame of that object from
			# startpage, page1, page2 respectively with 
			# for loop
			self.frames[F] = frame 

			frame.grid(row = 0, column = 0, sticky ="nsew")

		self.show_frame(StartPage)

	# to display the current frame passed as
	# parameter
	def show_frame(self, cont):
		frame = self.frames[cont]
		frame.tkraise()

# first window frame startpage

class StartPage(tk.Frame):
	def __init__(self, parent, controller): 
		tk.Frame.__init__(self, parent)
		
        
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
		current_directory = getcwd()
		print(current_directory)
		frame_number= r"\frame3"
		ASSETS_PATH =  Path(current_directory + r"\Screens\Assets" + frame_number)   
		print(ASSETS_PATH)

		def relative_to_assets(path: str) -> Path:
			return ASSETS_PATH / Path(path)



		def Writealignment_clicked():
			print("yazı hizalama")

		def optikread_clicked():
			print("opktik okuma ")

		def sestanima_clicked():
			print("sestanıma")






		
		

		#canvas 
		canvas = Canvas(self,bg = "#47C4B6",height = 320,width = 480,bd = 0,highlightthickness = 0,relief = "ridge")
		canvas.place(x = 0, y = 0)

		#button 1
		button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
		button_1 = Button(image=button_image_1,borderwidth=0,highlightthickness=0,command=optikread_clicked,relief="flat")
		button_1.place(x=19.0,y=107.0,width=125.34329223632812,height=126.0)
		#button 2

		button_image_2 = PhotoImage(file=relative_to_assets("button_2.png"))
		button_2 = Button(image=button_image_2,borderwidth=0,highlightthickness=0,command=Writealignment_clicked,relief="flat")
		#button_2.place(x=x2, y=y, width=125.34326171875, height=button_height)
		button_2.place(x=179.0,y=107.0,width=125.34326171875,height=126.0)

		#button 3
		button_image_3 = PhotoImage(file=relative_to_assets("button_3.png"))
		button_3 = Button(image=button_image_3,borderwidth=0,highlightthickness=0,command=sestanima_clicked,relief="flat")
		#button_3.place(x=x3, y=y, width=125.34326171875, height=button_height)
		button_3.place(x=337.0,y=107.0,width=125.34326171875,height=126.0)

		









		# label of frame Layout 2
		label = ttk.Label(self, text ="Startpage", font = LARGEFONT)
		
		# putting the grid in its place by using
		# grid
		label.grid(row = 0, column = 4, padx = 10, pady = 10) 

		
		button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
		button_1 = Button(self,image=button_image_1,borderwidth=0,highlightthickness=0,command=lambda : controller.show_frame(Page1),relief="flat")
		button_1.place(x=19.0,y=107.0,width=125.34329223632812,height=126.0)
		

		## button to show frame 2 with text layout2
		button2 = ttk.Button(self, text ="Page 2",
		command = lambda : controller.show_frame(Page2))
	
		# putting the button in its place by
		# using grid
		button2.grid(row = 2, column = 1, padx = 10, pady = 10)

		


# second window frame page1 
class Page1(tk.Frame):
	
	def __init__(self, parent, controller):
		
		tk.Frame.__init__(self, parent)
		label = ttk.Label(self, text ="Page 1", font = LARGEFONT)
		label.grid(row = 0, column = 4, padx = 10, pady = 10)

		# button to show frame 2 with text
		# layout2
		button1 = ttk.Button(self, text ="StartPage",
							command = lambda : controller.show_frame(StartPage))
	
		# putting the button in its place 
		# by using grid
		button1.grid(row = 1, column = 1, padx = 10, pady = 10)

		# button to show frame 2 with text
		# layout2
		button2 = ttk.Button(self, text ="Page 2",
							command = lambda : controller.show_frame(Page2))
	
		# putting the button in its place by 
		# using grid
		button2.grid(row = 2, column = 1, padx = 10, pady = 10)




# third window frame page2
class Page2(tk.Frame): 
	def __init__(self, parent, controller):
		tk.Frame.__init__(self, parent)
		label = ttk.Label(self, text ="Page 2", font = LARGEFONT)
		label.grid(row = 0, column = 4, padx = 10, pady = 10)

		# button to show frame 2 with text
		# layout2
		button1 = ttk.Button(self, text ="Page 1",
							command = lambda : controller.show_frame(Page1))
	
		# putting the button in its place by 
		# using grid
		button1.grid(row = 1, column = 1, padx = 10, pady = 10)

		# button to show frame 3 with text
		# layout3
		button2 = ttk.Button(self, text ="Startpage",
							command = lambda : controller.show_frame(StartPage))
	
		# putting the button in its place by
		# using grid
		button2.grid(row = 2, column = 1, padx = 10, pady = 10)


# Driver Code
app = tkinterApp()
app.mainloop()
