
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from os import error, getcwd
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


current_directory = getcwd()
print(current_directory)
frame_number= r"\frame0"
ASSETS_PATH =  Path(current_directory + r"\Screens\Assets" + frame_number)   
print(ASSETS_PATH)

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
#window.attributes('-fullscreen',True)
window.geometry("480x320")
window.configure(bg = "#47C4B6")


canvas = Canvas(
    window,
    bg = "#47C4B6",
    height = 320,
    width = 480,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=65.0,
    y=230.0,
    width=350.0,
    height=80.0
)

canvas.create_rectangle(
    15.0,
    21.0,
    465.0,
    221.0,
    fill="#F0E2E7",
    outline="")
window.resizable(False, False)
window.mainloop()
